stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
    params:
      - preprocessing.scale
      - preprocessing.encode
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    params:
      - model.params
      - training.test_size
      - training.random_state
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/processed/test.csv
    params:
      - model.params 
    outs:
      - experiments/results.json
    metrics:
      - metrics.json
